#!/bin/bash

declare -r -i SPACE=0
declare -r -i WALL1=1 # dark blue wall, 2 little stones at top-right corner
declare -r -i WALL2=2 # dark blue wall, 1 big stone at top-right corner
declare -r -i WALL3=3 # dark blue wall, fenced door
declare -r -i WALL4=4 # dark blue wall, fenced door with skeleton
#: '
declare -r -i MAPW=14
declare -r -i MAPH=15
declare -ai MAP
declare -r -ai TMAP=(
	$WALL1 $WALL1 $WALL2 $WALL1 $WALL2 $WALL1 $WALL2 $WALL1 $WALL1 $WALL2 $WALL1 $WALL1 $WALL2 $WALL1 
	$WALL3 $SPACE $SPACE $SPACE $WALL2 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL2 $SPACE $SPACE $SPACE $WALL2 $SPACE $SPACE $SPACE $WALL2 $SPACE $SPACE $SPACE $SPACE $WALL2
	$WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL3 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL2
	$WALL1 $SPACE $SPACE $SPACE $WALL2 $WALL1 $SPACE $WALL1 $WALL2 $WALL2 $WALL1 $SPACE $WALL1 $WALL1
	$WALL2 $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL4 $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $WALL4
	$WALL1 $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL2 $SPACE $SPACE $SPACE $WALL2 $WALL1 $SPACE $WALL1 $WALL1 $WALL2 $WALL1 $SPACE $WALL1 $WALL1
	$WALL3 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL2 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL1 $SPACE $SPACE $SPACE $WALL2 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL1
	$WALL3 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $WALL1 $SPACE $SPACE $SPACE $SPACE $WALL2
	$WALL2 $WALL1 $WALL1 $WALL1 $WALL2 $WALL1 $WALL2 $WALL1 $WALL1 $WALL2 $WALL2 $WALL2 $WALL2 $WALL2
)
#'
: '
declare -r -i MAPW=5
declare -r -i MAPH=5

declare -r -ai MAP=(
	$WALL1 $WALL1 $WALL1 $WALL1 $WALL1
	$WALL1 $SPACE $SPACE $SPACE $WALL1
	$WALL1 $SPACE $SPACE $SPACE $WALL2
	$WALL1 $SPACE $SPACE $SPACE $WALL3
	$WALL1 $WALL2 $WALL1 $WALL4 $WALL1
)
'

for (( i = 0; i < MAPH; i++ )); do
	for (( j = 0; j < MAPW; j++ )); do
		MAP[MAPW*i+j]=${TMAP[MAPW*j+i]}
	done
done 
